
;--- LUT0 ------------------------------

                ;       A B G R
                .dword $00000000
                .dword $00806C12    ; [11] balloon primary
                .dword $00411280    ; [12] balloon secondary
                .dword $00745720    ; [13] balloon basket
                .dword $00000000    ; [14]
                .dword $00757420    ; [15] plane primary
                .dword $00000000    ; [16]
                .dword $00000000    ; [17]
                .dword $00000000    ; [18]
                .dword $0024752E    ; [19] bombs
                .dword $00000000    ; [1A]
                .dword $00000000    ; [1B]
                .dword $00000000    ; [1C]
                .dword $00300400
                .dword $00400000
                .dword $009B4884

;--- LUT1 ------------------------------

                .dword $00000000
                .dword $000000e2    ; [01] balloon primary
                .dword $0053b8da    ; [02] balloon secondary
                .dword $00745720    ; [03] balloon basket
                .dword $00000000    ; [04]
                .dword $002C2492    ; [05] plane primary
                .dword $00000000    ; [06]
                .dword $00000000    ; [07]
                .dword $00000000    ; [08]
                .dword $0024752E    ; [09] bombs
                .dword $00000000    ; [0A]
                .dword $00000000    ; [0B]
                .dword $00000000    ; [0C]
                .dword $00300400
                .dword $00400000
                .dword $009b4884

;--------------------------------------
                .fill 960,$00
;--------------------------------------
